// Snapshot-based usage tracking. Idea: claude code pipes a JSON blob
// containing { rate_limits: { five_hour, seven_day, seven_day_sonnet } }
// to its statusLine command via stdin every UI refresh tick. We install
// a tiny shell script as that statusLine command for sessions we spawn,
// and the script dumps the JSON to ~/.deepthix/usage-snapshot.json.
// The frontend polls that file every 5s.
//
// Why this beats hitting /api/oauth/usage ourselves:
//   - No OAuth refresh dance (claude already has a fresh token in-process).
//   - No Cloudflare to bypass.
//   - No rate-limit risk (we never touch any Anthropic endpoint).
//   - Always live as long as the user has at least one Deepthix-spawned
//     claude session running.
//
// Cost: we pass `--settings` to every spawned claude with a tiny JSON
// pointing statusLine at our dumper. claude merges this with the user's
// own ~/.claude/settings.json so existing hooks etc. still work.

use std::path::PathBuf;

use crate::storage;

/// Where the dumper writes the latest snapshot JSON.
pub fn snapshot_path() -> std::io::Result<PathBuf> {
    Ok(storage::deepthix_dir()?.join("usage-snapshot.json"))
}

/// Where the dumper script lives.
fn dumper_script_path() -> std::io::Result<PathBuf> {
    Ok(storage::deepthix_dir()?.join("statusline-dumper.sh"))
}

/// The settings JSON we pass to claude via `--settings` so statusLine
/// points at our dumper. Merges with the user's own settings — claude
/// only overrides the statusLine block.
pub fn overlay_settings_path() -> std::io::Result<PathBuf> {
    Ok(storage::deepthix_dir()?.join("claude-overlay-settings.json"))
}

/// Separate MCP-only config we pass via `--mcp-config`. claude code
/// IGNORES `mcpServers` inside `--settings` files — MCP servers must
/// come from `--mcp-config` (or be registered globally via
/// `claude mcp add`). This file lists just the deepthix sidecar so
/// every Deepthix-spawned session can use its read tools.
pub fn mcp_config_path() -> std::io::Result<PathBuf> {
    Ok(storage::deepthix_dir()?.join("claude-mcp-config.json"))
}

/// Idempotently install the dumper script + the overlay settings file.
/// Safe to call repeatedly — only writes when the on-disk content
/// differs from the canonical version. Returns Ok(()) even if writes
/// fail because of a read-only home dir; callers log and proceed.
pub fn ensure_installed() -> std::io::Result<()> {
    let snapshot = snapshot_path()?;
    let snapshot_str = snapshot.to_string_lossy().into_owned();

    // Dumper script: read stdin, atomically write it to the snapshot
    // file (.tmp + mv so polling never reads a half-written file).
    // The statusline command MUST emit something on stdout; we echo an
    // empty string so claude's TUI gets a one-character statusline (a
    // single space) — invisible enough not to clutter the prompt.
    let script = format!(
        r#"#!/bin/bash
# Auto-generated by Deepthix Agent. Captures the {{ rate_limits, ... }}
# JSON claude pipes to statusLine via stdin and saves it to
# {snapshot_str}. The frontend polls that file for live usage data.
set -e
TMP="{snapshot_str}.tmp"
cat > "$TMP"
mv "$TMP" "{snapshot_str}"
# Empty statusline (single space — claude requires non-empty output).
printf ' '
"#
    );

    let dumper = dumper_script_path()?;
    if let Some(parent) = dumper.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let needs_write = match std::fs::read_to_string(&dumper) {
        Ok(existing) => existing != script,
        Err(_) => true,
    };
    if needs_write {
        std::fs::write(&dumper, script.as_bytes())?;
        // chmod +x — required for claude to spawn it. Unix-only: on
        // Windows there's no executable bit, the file extension is what
        // determines spawnability. The bash script is macOS-only anyway
        // (claude statusLine uses `bash`, not cmd.exe), so the whole
        // statusLine pipeline is effectively a no-op on Windows.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&dumper)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&dumper, perms)?;
        }
        tracing::info!(target: "deepthix::usage_snapshot", ?dumper, "installed dumper script");
    }

    let dumper_str = dumper.to_string_lossy().into_owned();

    // Resolve the MCP sidecar binary path. In dev it sits next to the
    // main app binary in target/debug/. In a bundled .app we'll need to
    // ship it via Tauri's sidecar config — for now we just look beside
    // the running executable, which works for both dev and any sidecar
    // copy that lands in the same dir.
    let mcp_bin = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.join("deepthix-mcp")))
        .filter(|p| p.exists());

    let overlay = serde_json::json!({
        "statusLine": {
            "type": "command",
            "command": dumper_str,
            "padding": 0,
        },
        // anthropics/claude-code#41007 — animated spinner glyphs
        // (`· ✢ * ✶ ✻ ✽`) have inconsistent widths in some monospace
        // fonts, which makes the box-drawing chars one row down jitter
        // by 1 column on every frame. Disabling the animations stops
        // that cascade. Has no effect on tool/output rendering.
        "prefersReducedMotion": true
    });
    let overlay_str = serde_json::to_string_pretty(&overlay).unwrap();
    let overlay_path = overlay_settings_path()?;
    let needs_write = match std::fs::read_to_string(&overlay_path) {
        Ok(existing) => existing != overlay_str,
        Err(_) => true,
    };
    if needs_write {
        std::fs::write(&overlay_path, overlay_str.as_bytes())?;
        tracing::info!(target: "deepthix::usage_snapshot", ?overlay_path, "installed overlay settings");
    }

    // MCP config — separate file because claude code ignores mcpServers
    // inside --settings files. This is the file we pass via
    // --mcp-config when spawning claude.
    if let Some(mcp_path) = mcp_bin {
        let mcp_str = mcp_path.to_string_lossy().into_owned();
        let mcp_config = serde_json::json!({
            "mcpServers": {
                "deepthix": {
                    "type": "stdio",
                    "command": mcp_str,
                    "args": []
                }
            }
        });
        let mcp_config_str = serde_json::to_string_pretty(&mcp_config).unwrap();
        let mcp_config_file = mcp_config_path()?;
        let needs_write = match std::fs::read_to_string(&mcp_config_file) {
            Ok(existing) => existing != mcp_config_str,
            Err(_) => true,
        };
        if needs_write {
            std::fs::write(&mcp_config_file, mcp_config_str.as_bytes())?;
            tracing::info!(target: "deepthix::usage_snapshot", ?mcp_config_file, "installed MCP config");
        }
    } else {
        tracing::warn!(target: "deepthix::usage_snapshot", "deepthix-mcp binary not found beside app — orchestrator tools disabled");
    }

    Ok(())
}

#[derive(Debug, serde::Serialize, serde::Deserialize, Default)]
pub struct UsageSnapshot {
    /// Raw JSON the dumper captured (string so we don't lock the schema).
    /// Empty when no snapshot file exists yet.
    pub body: String,
    /// File mtime in epoch ms; 0 if absent.
    pub mtime_ms: u64,
}

/// Read whatever the dumper has captured. Returns an empty body when
/// no claude session has run since install.
#[tauri::command]
pub fn read_claude_usage_snapshot() -> Result<UsageSnapshot, String> {
    let path = snapshot_path().map_err(|e| e.to_string())?;
    let body = match std::fs::read_to_string(&path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(UsageSnapshot::default()),
        Err(e) => return Err(e.to_string()),
    };
    let mtime_ms = std::fs::metadata(&path)
        .ok()
        .and_then(|m| m.modified().ok())
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    Ok(UsageSnapshot { body, mtime_ms })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ensure_installed_creates_files() {
        // Best-effort — writes under the user's real home so we just
        // verify it doesn't error.
        let result = ensure_installed();
        assert!(result.is_ok(), "got {:?}", result);
        assert!(dumper_script_path().unwrap().exists());
        assert!(overlay_settings_path().unwrap().exists());
    }

    #[test]
    fn snapshot_returns_empty_when_missing() {
        // Best-effort — assumes no snapshot exists yet (or stale-but-readable).
        let r = read_claude_usage_snapshot();
        assert!(r.is_ok());
    }
}
